### ISSUE TITLE
Open index.html with firefox/chrome doesn't work

### ISSUE THREAD

**Issue by edimitchel** [mcgivrer/ufo#14]
Hi mister givrer!

I test your game, and as says the README, open with firefox should display the game.

But, something goes wrong.
Javascript Modules seems to work only with served files. I got CORS error from firefox (same with Chrome).
Another solution (npm run dev) doesn't not exist, so doesn't work too..

I was able to test using `npx live-server .`

**Comment by mcgivrer** [comment]
Good point, I am now using the 'yarn' tools and parcel to run a dev server locally.

I'll update the readme file for that !
